apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"grafana"},"name":"grafana","namespace":"monitoring"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"grafana"}},"template":{"metadata":{"labels":{"app":"grafana"}},"spec":{"containers":[{"env":[{"name":"GF_SECURITY_ADMIN_PASSWORD","value":"admin123"},{"name":"GF_SECURITY_ADMIN_USER","value":"admin"}],"image":"grafana/grafana:10.0.0","name":"grafana","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"200m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"mountPath":"/var/lib/grafana","name":"grafana-storage"},{"mountPath":"/etc/grafana/provisioning/datasources","name":"grafana-datasources"},{"mountPath":"/etc/grafana/provisioning/dashboards","name":"grafana-dashboards"}]}],"volumes":[{"emptyDir":{},"name":"grafana-storage"},{"configMap":{"name":"grafana-datasources"},"name":"grafana-datasources"},{"configMap":{"name":"grafana-dashboards"},"name":"grafana-dashboards"}]}}}}
  creationTimestamp: "2025-09-22T13:55:08Z"
  generation: 1
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: "1805"
  uid: b236f4b2-5b76-4368-b01b-72355557f3d2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
    spec:
      containers:
      - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin123
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        image: grafana/grafana:10.0.0
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: grafana-storage
      - configMap:
          defaultMode: 420
          name: grafana-datasources
        name: grafana-datasources
      - configMap:
          defaultMode: 420
          name: grafana-dashboards
        name: grafana-dashboards
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-22T13:55:15Z"
    lastUpdateTime: "2025-09-22T13:55:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-09-22T13:55:08Z"
    lastUpdateTime: "2025-09-22T13:55:15Z"
    message: ReplicaSet "grafana-dd46bb9bf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
