apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grafana"},"name":"grafana-service","namespace":"monitoring"},"spec":{"ports":[{"nodePort":30030,"port":3000,"targetPort":3000}],"selector":{"app":"grafana"},"type":"NodePort"}}
  creationTimestamp: "2025-09-22T13:55:08Z"
  labels:
    app: grafana
  name: grafana-service
  namespace: monitoring
  resourceVersion: "1780"
  uid: 9813a738-0718-4b87-9be8-aef52abbf132
spec:
  clusterIP: 10.96.202.129
  clusterIPs:
  - 10.96.202.129
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30030
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
