apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9100","prometheus.io/scrape":"true"},"labels":{"app":"node-exporter","component":"node-exporter"},"name":"node-exporter-service","namespace":"monitoring"},"spec":{"ports":[{"name":"http-metrics","port":9100,"protocol":"TCP","targetPort":9100}],"selector":{"app":"node-exporter","component":"node-exporter"},"type":"ClusterIP"}}
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-09-23T06:30:17Z"
  labels:
    app: node-exporter
    component: node-exporter
  name: node-exporter-service
  namespace: monitoring
  resourceVersion: "31490"
  uid: a360fafc-af8b-495a-b8ea-06790cc20554
spec:
  clusterIP: 10.96.140.95
  clusterIPs:
  - 10.96.140.95
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
    component: node-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
